trigger:
- none # only triggered via pipelines

variables:
  - template: 'templates/variables.yml'

pool:
  vmImage: $(VM_IMAGE)
strategy:
  matrix:
    Python310:
      python.version: $(PYTHON_VERSION)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --user pipenv
    pipenv install
  displayName: 'Install dependencies'

- script: |
    pipenv run pytest
  displayName: 'pytest'
